import Navbar from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextThemeProvider, ReactQueryProvider, SessionProvider } from '@/components/providers'
import { getServerSession } from 'next-auth'
import { Toaster } from '@/components/ui/toaster'
import { SiteFooter } from '@/components/site-footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()

  return (
    <html lang="en">

      <body className={inter.className}>
        <SessionProvider session={session}>
          <ReactQueryProvider>
            <NextThemeProvider>
              <Navbar />
              <div className='mx-auto sm:px-24 py-4 text-xl font-semibold'>
                {children}
              </div>
              <Toaster />
              <SiteFooter />
            </NextThemeProvider>
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
